// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://daebsjsckmezolxldqqp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRhZWJzanNja21lem9seGxkcXFwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5Mjk3NDMsImV4cCI6MjA2NDUwNTc0M30.WI_a-id1zc6WgWB_8v6YJDzvxGV6SYc_27kefI8mjmU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);